Repository KUSITMS-29th-TEAM-D/backend, pull requests merged in 2024-05, with the labels that each got.

#11 [feat]CICD Test
  .github/workflows/cicd.yml
  Dockerfile
  build.gradle
  src/main/java/kusitms/jangkku/domain/HealthCheckAPI.java
Labels: feat

#13 [feat] : 레지스터 토큰 & 기본정보 입력 API & 닉네임 중복 체크 API 구현
  src/main/java/kusitms/jangkku/domain/interest/dao/InterestRepository.java
  src/main/java/kusitms/jangkku/domain/interest/domain/Interest.java
  src/main/java/kusitms/jangkku/domain/keyword/dao/KeywordRepository.java
  src/main/java/kusitms/jangkku/domain/keyword/domain/Keyword.java
  src/main/java/kusitms/jangkku/domain/user/api/UserController.java
  src/main/java/kusitms/jangkku/domain/user/application/UserService.java
  src/main/java/kusitms/jangkku/domain/user/application/UserServiceImpl.java
  src/main/java/kusitms/jangkku/domain/user/dao/UserRepository.java
  src/main/java/kusitms/jangkku/domain/user/domain/User.java
  src/main/java/kusitms/jangkku/domain/user/dto/UserDto.java
  src/main/java/kusitms/jangkku/domain/user/exception/UserErrorResult.java
  src/main/java/kusitms/jangkku/domain/userinterest/dao/UserInterestRepository.java
  src/main/java/kusitms/jangkku/domain/userinterest/domain/UserInterest.java
  src/main/java/kusitms/jangkku/domain/userkeyword/dao/UserKeywordRepository.java
  src/main/java/kusitms/jangkku/domain/userkeyword/domain/UserKeyword.java
  src/main/java/kusitms/jangkku/global/auth/application/OAuthLoginSuccessHandler.java
  src/main/java/kusitms/jangkku/global/common/ApiResponse.java
  src/main/java/kusitms/jangkku/global/common/constant/SuccessStatus.java
  src/main/java/kusitms/jangkku/global/util/JwtUtil.java
  src/main/resources/application.yml
  src/main/resources/data.sql
Labels: enhancement

#16 [feat] : 테스트 여부 쿼리 파라미터 추가
  src/main/java/kusitms/jangkku/domain/persona/dao/DefinePersonaKeywordRepository.java
  src/main/java/kusitms/jangkku/domain/persona/dao/DefinePersonaRepository.java
  src/main/java/kusitms/jangkku/domain/persona/domain/DefinePersona.java
  src/main/java/kusitms/jangkku/domain/persona/domain/DefinePersonaKeyword.java
  src/main/java/kusitms/jangkku/domain/user/application/UserServiceImpl.java
  src/main/java/kusitms/jangkku/domain/user/dao/UserInterestRepository.java
  src/main/java/kusitms/jangkku/domain/user/dao/UserKeywordRepository.java
  src/main/java/kusitms/jangkku/domain/user/domain/UserInterest.java
  src/main/java/kusitms/jangkku/domain/user/domain/UserKeyword.java
  src/main/java/kusitms/jangkku/global/auth/application/OAuthLoginSuccessHandler.java
  src/main/java/kusitms/jangkku/global/util/HealthCheckAPI.java
Labels: enhancement, feat

#19 [feat] : CLOVA Studio api 연동
  build.gradle
  src/main/java/kusitms/jangkku/domain/chatbot/api/ChatBotController.java
  src/main/java/kusitms/jangkku/domain/chatbot/application/ChatBotService.java
  src/main/java/kusitms/jangkku/domain/chatbot/dto/ChatBotDto.java
  src/main/java/kusitms/jangkku/domain/chatbot/dto/Message.java
  src/main/java/kusitms/jangkku/global/config/ChatBotConfig.java
  src/main/java/kusitms/jangkku/global/config/WebClientConfig.java
  src/main/resources/application.yml
Labels: feat

#20 [feat]Chatgpt api 연동2
  src/main/java/kusitms/jangkku/domain/chatbot/api/ChatBotController.java
  src/main/java/kusitms/jangkku/domain/chatbot/application/ChatBotService.java
  src/main/java/kusitms/jangkku/domain/chatbot/dto/ChatBotDto.java
  src/main/java/kusitms/jangkku/domain/chatbot/dto/Message.java
  src/main/java/kusitms/jangkku/domain/chatbot/dto/Result.java
Labels: feat

#23 [refactor] : 조각 결과 응답 데이터 추가
  src/main/java/kusitms/jangkku/domain/persona/application/DefinePersonaServiceImpl.java
  src/main/java/kusitms/jangkku/domain/persona/constant/Content.java
  src/main/java/kusitms/jangkku/domain/persona/dto/DefinePersonaDto.java
Labels: refactor

#24 [feat] : 조각 조회 API 구현 (GET)
  build.gradle
  src/main/java/kusitms/jangkku/domain/persona/api/DefinePersonaController.java
  src/main/java/kusitms/jangkku/domain/persona/application/DefinePersonaService.java
  src/main/java/kusitms/jangkku/domain/persona/application/DefinePersonaServiceImpl.java
  src/main/java/kusitms/jangkku/domain/persona/constant/Content.java
  src/main/java/kusitms/jangkku/domain/persona/constant/PersonaSuccessStatus.java
  src/main/java/kusitms/jangkku/domain/persona/dao/DefinePersonaKeywordRepository.java
  src/main/java/kusitms/jangkku/domain/persona/dao/DefinePersonaRepository.java
  src/main/java/kusitms/jangkku/domain/persona/domain/DefinePersona.java
  src/main/java/kusitms/jangkku/domain/persona/dto/DefinePersonaDto.java
  src/main/java/kusitms/jangkku/domain/persona/exception/PersonaErrorResult.java
Labels: feat

#26 [feat] : 프로필 사진 & 정보 조회 및 수정 API 구현
  build.gradle
  src/main/java/kusitms/jangkku/domain/auth/application/OAuthLoginSuccessHandler.java
  src/main/java/kusitms/jangkku/domain/user/api/UserController.java
  src/main/java/kusitms/jangkku/domain/user/application/UserService.java
  src/main/java/kusitms/jangkku/domain/user/application/UserServiceImpl.java
  src/main/java/kusitms/jangkku/domain/user/constant/UserSuccessStatus.java
  src/main/java/kusitms/jangkku/domain/user/domain/User.java
  src/main/java/kusitms/jangkku/domain/user/dto/UserDto.java
  src/main/java/kusitms/jangkku/global/config/NcpConfig.java
  src/main/java/kusitms/jangkku/global/exception/GlobalExceptionHandler.java
  src/main/java/kusitms/jangkku/global/exception/S3ErrorResult.java
  src/main/java/kusitms/jangkku/global/exception/S3Exception.java
  src/main/java/kusitms/jangkku/global/util/S3Util.java
  src/main/resources/application.yml
Labels: feat

#27 [feat] : 유저 로그아웃 API 구현 (POST)
  src/main/java/kusitms/jangkku/domain/user/api/UserController.java
  src/main/java/kusitms/jangkku/domain/user/application/UserService.java
  src/main/java/kusitms/jangkku/domain/user/application/UserServiceImpl.java
  src/main/java/kusitms/jangkku/domain/user/constant/UserSuccessStatus.java
Labels: feat

#29 [Feat] : CLOVAStudio 대화 로직 구현
  src/main/java/kusitms/jangkku/domain/chatbot/api/ChatBotController.java
  src/main/java/kusitms/jangkku/domain/chatbot/application/ChatBotService.java
  src/main/java/kusitms/jangkku/domain/chatbot/dto/ChatBotDto.java
  src/main/java/kusitms/jangkku/domain/chatbot/dto/ChatBotUserDto.java
  src/main/java/kusitms/jangkku/domain/chatbot/dto/Message.java
Labels: feat

#31 [refactor] : 로그아웃 시 액세스 토큰 필요 없도록 변경
  src/main/java/kusitms/jangkku/domain/user/api/UserController.java
  src/main/java/kusitms/jangkku/domain/user/application/UserService.java
  src/main/java/kusitms/jangkku/domain/user/application/UserServiceImpl.java
Labels: refactor

#32 [refactor] : 파일 접근 허용으로 변경
  src/main/java/kusitms/jangkku/global/util/S3Util.java
Labels: refactor

#34 [feat] : 설계하기 페르소나 생성 API 구현 (POST)
  src/main/java/kusitms/jangkku/domain/chatbot/application/ChatBotService.java
  src/main/java/kusitms/jangkku/domain/chatbot/dto/ChatBotDto.java
  src/main/java/kusitms/jangkku/domain/chatbot/dto/Message.java
  src/main/java/kusitms/jangkku/domain/persona/api/DesignPersonaController.java
  src/main/java/kusitms/jangkku/domain/persona/application/DesignPersonaService.java
  src/main/java/kusitms/jangkku/domain/persona/application/DesignPersonaServiceImpl.java
  src/main/java/kusitms/jangkku/domain/persona/constant/DesignStage.java
  src/main/java/kusitms/jangkku/domain/persona/constant/PersonaSuccessStatus.java
  src/main/java/kusitms/jangkku/domain/persona/dao/DesignPersonaAbilityRepository.java
  src/main/java/kusitms/jangkku/domain/persona/dao/DesignPersonaDistinctionRepository.java
  src/main/java/kusitms/jangkku/domain/persona/dao/DesignPersonaFieldRepository.java
  src/main/java/kusitms/jangkku/domain/persona/dao/DesignPersonaPlatformRepository.java
  src/main/java/kusitms/jangkku/domain/persona/dao/DesignPersonaRepository.java
  src/main/java/kusitms/jangkku/domain/persona/domain/DesignPersona.java
  src/main/java/kusitms/jangkku/domain/persona/domain/DesignPersonaAbility.java
  src/main/java/kusitms/jangkku/domain/persona/domain/DesignPersonaDistinction.java
  src/main/java/kusitms/jangkku/domain/persona/domain/DesignPersonaField.java
  src/main/java/kusitms/jangkku/domain/persona/domain/DesignPersonaPlatform.java
  src/main/java/kusitms/jangkku/domain/persona/dto/DesignPersonaDto.java
  src/main/java/kusitms/jangkku/global/util/StringUtil.java
Labels: feat

#36 [refactor] : 정의하기 페르소나 로직 리팩토링 완료
  src/main/java/kusitms/jangkku/domain/persona/api/DefinePersonaController.java
  src/main/java/kusitms/jangkku/domain/persona/application/DefinePersonaService.java
  src/main/java/kusitms/jangkku/domain/persona/application/DefinePersonaServiceImpl.java
  src/main/java/kusitms/jangkku/domain/persona/constant/Content.java
  src/main/java/kusitms/jangkku/domain/persona/dao/DefinePersonaRepository.java
  src/main/java/kusitms/jangkku/domain/persona/domain/DefinePersona.java
  src/main/java/kusitms/jangkku/domain/persona/dto/DefinePersonaDto.java
Labels: refactor

#38 [feat] : S3 CORS 설정 추가
  src/main/java/kusitms/jangkku/global/config/NcpConfig.java
  src/main/java/kusitms/jangkku/global/util/S3Util.java
Labels: feat

#39 [feat] : BaseEntity 생성
  src/main/java/kusitms/jangkku/global/common/dao/BaseEntity.java
Labels: feat

#41 [refactor] : BaseEntity 추상 클래스 추가 & DTO of 메서드 추가
  src/main/java/kusitms/jangkku/JangkkuApplication.java
  src/main/java/kusitms/jangkku/domain/auth/application/OAuthLoginSuccessHandler.java
  src/main/java/kusitms/jangkku/domain/interest/domain/Interest.java
  src/main/java/kusitms/jangkku/domain/keyword/domain/Keyword.java
  src/main/java/kusitms/jangkku/domain/persona/application/DefinePersonaServiceImpl.java
  src/main/java/kusitms/jangkku/domain/persona/application/DesignPersonaServiceImpl.java
  src/main/java/kusitms/jangkku/domain/persona/domain/DesignPersona.java
  src/main/java/kusitms/jangkku/domain/persona/domain/DesignPersonaAbility.java
  src/main/java/kusitms/jangkku/domain/persona/domain/DesignPersonaDistinction.java
  src/main/java/kusitms/jangkku/domain/persona/domain/DesignPersonaField.java
  src/main/java/kusitms/jangkku/domain/persona/domain/DesignPersonaPlatform.java
  src/main/java/kusitms/jangkku/domain/persona/dto/DefinePersonaDto.java
  src/main/java/kusitms/jangkku/domain/persona/dto/DesignPersonaDto.java
  src/main/java/kusitms/jangkku/domain/token/api/TokenController.java
  src/main/java/kusitms/jangkku/domain/token/application/TokenService.java
  src/main/java/kusitms/jangkku/domain/token/application/TokenServiceImpl.java
  src/main/java/kusitms/jangkku/domain/token/dto/TokenDto.java
  src/main/java/kusitms/jangkku/domain/token/dto/response/TokenResponse.java
  src/main/java/kusitms/jangkku/domain/user/application/UserServiceImpl.java
  src/main/java/kusitms/jangkku/domain/user/dao/UserOnboardingInfoRepository.java
  src/main/java/kusitms/jangkku/domain/user/dao/UserRepository.java
  src/main/java/kusitms/jangkku/domain/user/domain/User.java
  src/main/java/kusitms/jangkku/domain/user/domain/UserInterest.java
  src/main/java/kusitms/jangkku/domain/user/domain/UserKeyword.java
  src/main/java/kusitms/jangkku/domain/user/domain/UserOnboardingInfo.java
  src/main/java/kusitms/jangkku/domain/user/dto/UserDto.java
  src/main/java/kusitms/jangkku/global/common/dao/BaseEntity.java
  src/main/resources/data.sql
Labels: refactor

#42 [feat] : 설계하기 페르소나 조회 API 구현 (GET)
  src/main/java/kusitms/jangkku/domain/interest/dao/InterestRepository.java
  src/main/java/kusitms/jangkku/domain/keyword/dao/KeywordRepository.java
  src/main/java/kusitms/jangkku/domain/persona/api/DesignPersonaController.java
  src/main/java/kusitms/jangkku/domain/persona/application/DefinePersonaServiceImpl.java
  src/main/java/kusitms/jangkku/domain/persona/application/DesignPersonaService.java
  src/main/java/kusitms/jangkku/domain/persona/application/DesignPersonaServiceImpl.java
  src/main/java/kusitms/jangkku/domain/persona/constant/PersonaSuccessStatus.java
  src/main/java/kusitms/jangkku/domain/persona/dao/DefinePersonaKeywordRepository.java
  src/main/java/kusitms/jangkku/domain/persona/dao/DefinePersonaRepository.java
  src/main/java/kusitms/jangkku/domain/persona/dao/DesignPersonaAbilityRepository.java
  src/main/java/kusitms/jangkku/domain/persona/dao/DesignPersonaDistinctionRepository.java
  src/main/java/kusitms/jangkku/domain/persona/dao/DesignPersonaFieldRepository.java
  src/main/java/kusitms/jangkku/domain/persona/dao/DesignPersonaPlatformRepository.java
  src/main/java/kusitms/jangkku/domain/persona/dao/DesignPersonaRepository.java
  src/main/java/kusitms/jangkku/domain/persona/dto/DesignPersonaDto.java
  src/main/java/kusitms/jangkku/domain/user/dao/UserInterestRepository.java
  src/main/java/kusitms/jangkku/domain/user/dao/UserKeywordRepository.java
  src/main/java/kusitms/jangkku/domain/user/dao/UserOnboardingInfoRepository.java
  src/main/java/kusitms/jangkku/domain/user/dao/UserRepository.java
Labels: feat

#44 돌아보기 페르소나 질문 생성 API 구현 (POST)
  src/main/java/kusitms/jangkku/JangkkuApplication.java
  src/main/java/kusitms/jangkku/domain/chatbot/api/ChatBotController.java
  src/main/java/kusitms/jangkku/domain/chatbot/application/ChatBotService.java
  src/main/java/kusitms/jangkku/domain/chatbot/dto/Result.java
  src/main/java/kusitms/jangkku/domain/clova/application/ClovaService.java
  src/main/java/kusitms/jangkku/domain/clova/application/ClovaServiceImpl.java
  src/main/java/kusitms/jangkku/domain/clova/dto/ClovaDto.java
  src/main/java/kusitms/jangkku/domain/clova/dto/ClovaUserDto.java
  src/main/java/kusitms/jangkku/domain/clova/dto/Message.java
  src/main/java/kusitms/jangkku/domain/clova/dto/Result.java
  src/main/java/kusitms/jangkku/domain/persona/api/DiscoverPersonaController.java
  src/main/java/kusitms/jangkku/domain/persona/application/DesignPersonaServiceImpl.java
  src/main/java/kusitms/jangkku/domain/persona/application/DiscoverPersonaService.java
  src/main/java/kusitms/jangkku/domain/persona/application/DiscoverPersonaServiceImpl.java
  src/main/java/kusitms/jangkku/domain/persona/constant/PersonaSuccessStatus.java
  src/main/java/kusitms/jangkku/domain/persona/constant/Question.java
  src/main/java/kusitms/jangkku/domain/persona/dao/DiscoverPersonaChattingRepository.java
  src/main/java/kusitms/jangkku/domain/persona/dao/DiscoverPersonaKeywordRepository.java
  src/main/java/kusitms/jangkku/domain/persona/dao/DiscoverPersonaRepository.java
  src/main/java/kusitms/jangkku/domain/persona/domain/DiscoverPersona.java
  src/main/java/kusitms/jangkku/domain/persona/domain/DiscoverPersonaChatting.java
  src/main/java/kusitms/jangkku/domain/persona/domain/DiscoverPersonaKeyword.java
  src/main/java/kusitms/jangkku/domain/persona/dto/DiscoverPersonaDto.java
  src/main/java/kusitms/jangkku/domain/persona/exception/PersonaErrorResult.java
  src/main/java/kusitms/jangkku/global/config/JpaConfig.java
  src/main/java/kusitms/jangkku/global/util/NumberUtil.java
Labels: feat, refactor

#45 [feat] : 돌아보기 페르소나 공감 & 요약 API 구현 (POST)
  src/main/java/kusitms/jangkku/domain/clova/application/ClovaService.java
  src/main/java/kusitms/jangkku/domain/clova/application/ClovaServiceImpl.java
  src/main/java/kusitms/jangkku/domain/clova/dto/ClovaDto.java
  src/main/java/kusitms/jangkku/domain/clova/dto/Message.java
  src/main/java/kusitms/jangkku/domain/persona/api/DiscoverPersonaController.java
  src/main/java/kusitms/jangkku/domain/persona/application/DiscoverPersonaService.java
  src/main/java/kusitms/jangkku/domain/persona/application/DiscoverPersonaServiceImpl.java
  src/main/java/kusitms/jangkku/domain/persona/constant/PersonaSuccessStatus.java
  src/main/java/kusitms/jangkku/domain/persona/domain/DiscoverPersonaChatting.java
  src/main/java/kusitms/jangkku/domain/persona/dto/DiscoverPersonaDto.java
  src/main/java/kusitms/jangkku/domain/persona/exception/PersonaErrorResult.java
Labels: feat

#46 [fix] : 가장 최근에 생성된 페르소나만 반환하도록 수정
  src/main/java/kusitms/jangkku/domain/persona/application/DesignPersonaServiceImpl.java
  src/main/java/kusitms/jangkku/domain/persona/application/DiscoverPersonaServiceImpl.java
  src/main/java/kusitms/jangkku/domain/persona/dao/DesignPersonaRepository.java
  src/main/java/kusitms/jangkku/domain/persona/dto/DiscoverPersonaDto.java
Labels: fix

#47 [feat] : 채팅 내역 조회 API 구현 (GET)
  src/main/java/kusitms/jangkku/domain/persona/api/DiscoverPersonaController.java
  src/main/java/kusitms/jangkku/domain/persona/application/DiscoverPersonaService.java
  src/main/java/kusitms/jangkku/domain/persona/application/DiscoverPersonaServiceImpl.java
  src/main/java/kusitms/jangkku/domain/persona/constant/PersonaSuccessStatus.java
  src/main/java/kusitms/jangkku/domain/persona/dao/DiscoverPersonaChattingRepository.java
  src/main/java/kusitms/jangkku/domain/persona/dao/DiscoverPersonaRepository.java
  src/main/java/kusitms/jangkku/domain/persona/dto/DiscoverPersonaDto.java
Labels: feat, fix

#48 [ refactor] : 비로그인 전용 정의하기 페르소나 생성 API 구현 (POST)
  src/main/java/kusitms/jangkku/domain/persona/api/DefinePersonaController.java
  src/main/java/kusitms/jangkku/domain/persona/application/DefinePersonaService.java
  src/main/java/kusitms/jangkku/domain/persona/application/DefinePersonaServiceImpl.java
  src/main/java/kusitms/jangkku/global/exception/GlobalExceptionHandler.java
Labels: refactor

#49 [feat] : 답변 요약 내역 조회 API 구현 (GET)
  src/main/java/kusitms/jangkku/domain/persona/api/DiscoverPersonaController.java
  src/main/java/kusitms/jangkku/domain/persona/application/DiscoverPersonaService.java
  src/main/java/kusitms/jangkku/domain/persona/application/DiscoverPersonaServiceImpl.java
  src/main/java/kusitms/jangkku/domain/persona/constant/PersonaSuccessStatus.java
  src/main/java/kusitms/jangkku/domain/persona/dto/DiscoverPersonaDto.java
Labels: feat

#50 [fix] : 설계하기 페르소나 비로그인도 되던 오류 수정
  src/main/java/kusitms/jangkku/domain/persona/api/DesignPersonaController.java
Labels: fix

#51 [feat, refactor] : 초기 삽입문 추가 & 에러 처리 방식 변경
  src/main/java/kusitms/jangkku/domain/persona/dto/DefinePersonaDto.java
  src/main/java/kusitms/jangkku/domain/user/domain/User.java
  src/main/java/kusitms/jangkku/domain/user/domain/UserOnboardingInfo.java
  src/main/resources/data.sql
Labels: feat, refactor

#53 [feat] : 프로그램 전체 조회 페이지, 상세 페이지 조회 api
  src/main/java/kusitms/jangkku/domain/keyword/domain/Keyword.java
  src/main/java/kusitms/jangkku/domain/program/api/ProgramController.java
  src/main/java/kusitms/jangkku/domain/program/application/ProgramService.java
  src/main/java/kusitms/jangkku/domain/program/application/ProgramServiceImpl.java
  src/main/java/kusitms/jangkku/domain/program/constant/FORM.java
  src/main/java/kusitms/jangkku/domain/program/dao/BrandingRepository.java
  src/main/java/kusitms/jangkku/domain/program/dao/SelfUnderstandingsRepository.java
  src/main/java/kusitms/jangkku/domain/program/domain/Branding.java
  src/main/java/kusitms/jangkku/domain/program/domain/ProgramProvider.java
  src/main/java/kusitms/jangkku/domain/program/domain/ProgramsImageKeyword.java
  src/main/java/kusitms/jangkku/domain/program/domain/ProgramsInterest.java
  src/main/java/kusitms/jangkku/domain/program/domain/SelfUnderstanding.java
  src/main/java/kusitms/jangkku/domain/program/dto/ProgramDetailDto.java
  src/main/java/kusitms/jangkku/domain/program/dto/ProgramDto.java
  src/main/java/kusitms/jangkku/domain/program/exception/ProgramErrorResult.java
  src/main/java/kusitms/jangkku/domain/program/exception/ProgramException.java
  src/main/java/kusitms/jangkku/domain/user/dao/UserInterestRepository.java
  src/main/java/kusitms/jangkku/domain/user/dao/UserKeywordRepository.java
Labels: feat, refactor

#55 [Feat] : 프로그램 페이지 필터 api
  src/main/java/kusitms/jangkku/domain/program/api/ProgramController.java
  src/main/java/kusitms/jangkku/domain/program/application/ProgramService.java
  src/main/java/kusitms/jangkku/domain/program/application/ProgramServiceImpl.java
  src/main/java/kusitms/jangkku/domain/program/constant/FORM.java
  src/main/java/kusitms/jangkku/domain/program/dao/SelfUnderstandingsRepository.java
  src/main/java/kusitms/jangkku/domain/program/domain/ProgramsImageKeyword.java
  src/main/java/kusitms/jangkku/domain/program/dto/ProgramDetailDto.java
  src/main/java/kusitms/jangkku/domain/program/dto/ProgramDto.java
  src/main/java/kusitms/jangkku/domain/program/exception/ProgramErrorResult.java
Labels: feat

#56 [feat] : 카테고리별 채팅 다시하기 API 구현 (POST)
  src/main/java/kusitms/jangkku/domain/persona/api/DiscoverPersonaController.java
  src/main/java/kusitms/jangkku/domain/persona/application/DiscoverPersonaService.java
  src/main/java/kusitms/jangkku/domain/persona/application/DiscoverPersonaServiceImpl.java
  src/main/java/kusitms/jangkku/domain/persona/constant/PersonaSuccessStatus.java
  src/main/java/kusitms/jangkku/domain/persona/domain/DesignPersona.java
  src/main/java/kusitms/jangkku/domain/persona/domain/DiscoverPersonaKeyword.java
  src/main/java/kusitms/jangkku/domain/persona/dto/DiscoverPersonaDto.java
  src/main/java/kusitms/jangkku/domain/user/domain/User.java
  src/main/java/kusitms/jangkku/domain/user/domain/UserOnboardingInfo.java
Labels: feat

#57 [feat] : 대화 완료 여부 조회 API 구현 (GET)
  src/main/java/kusitms/jangkku/domain/persona/api/DiscoverPersonaController.java
  src/main/java/kusitms/jangkku/domain/persona/application/DefinePersonaServiceImpl.java
  src/main/java/kusitms/jangkku/domain/persona/application/DesignPersonaServiceImpl.java
  src/main/java/kusitms/jangkku/domain/persona/application/DiscoverPersonaService.java
  src/main/java/kusitms/jangkku/domain/persona/application/DiscoverPersonaServiceImpl.java
  src/main/java/kusitms/jangkku/domain/persona/constant/PersonaSuccessStatus.java
  src/main/java/kusitms/jangkku/domain/persona/dao/DiscoverPersonaRepository.java
  src/main/java/kusitms/jangkku/domain/persona/dto/DiscoverPersonaDto.java
  src/main/java/kusitms/jangkku/domain/user/application/UserServiceImpl.java
  src/main/java/kusitms/jangkku/global/util/JwtUtil.java
Labels: feat

#58 [refactor] : 프롬프팅 문구 인코딩 처리하여 환경변수로 변경
  src/main/java/kusitms/jangkku/domain/clova/dto/Message.java
  src/main/resources/application.yml
Labels: refactor

#60 [feat] 메인홈 프로그램 api
  src/main/java/kusitms/jangkku/domain/program/api/ProgramController.java
  src/main/java/kusitms/jangkku/domain/program/application/ProgramService.java
  src/main/java/kusitms/jangkku/domain/program/application/ProgramServiceImpl.java
  src/main/java/kusitms/jangkku/domain/program/dto/ProgramsHomeDto.java
Labels: refactor

#64 [feat] 메인페이지 비로그인 브랜딩 조회
  src/main/java/kusitms/jangkku/domain/program/api/ProgramController.java
  src/main/java/kusitms/jangkku/domain/program/application/ProgramService.java
  src/main/java/kusitms/jangkku/domain/program/application/ProgramServiceImpl.java
  src/main/java/kusitms/jangkku/domain/program/dao/BrandingRepository.java
Labels: feat

#68 [feat] : 돌아보기 페르소나 키워드 전체 조회 API 구현 (GET)
  src/main/java/kusitms/jangkku/domain/persona/api/DiscoverPersonaController.java
  src/main/java/kusitms/jangkku/domain/persona/application/DiscoverPersonaService.java
  src/main/java/kusitms/jangkku/domain/persona/application/DiscoverPersonaServiceImpl.java
  src/main/java/kusitms/jangkku/domain/persona/constant/PersonaSuccessStatus.java
  src/main/java/kusitms/jangkku/domain/persona/dao/DiscoverPersonaKeywordRepository.java
  src/main/java/kusitms/jangkku/domain/persona/dto/DiscoverPersonaDto.java
Labels: feat

#69 [feat] : 경험 신청하기 api
  src/main/java/kusitms/jangkku/domain/program/api/ProgramController.java
  src/main/java/kusitms/jangkku/domain/program/application/ProgramService.java
  src/main/java/kusitms/jangkku/domain/program/application/ProgramServiceImpl.java
  src/main/java/kusitms/jangkku/domain/program/constant/ProgramSuccessStatus.java
  src/main/java/kusitms/jangkku/domain/program/dao/ProgramParticipantsRepository.java
  src/main/java/kusitms/jangkku/domain/program/domain/Branding.java
  src/main/java/kusitms/jangkku/domain/program/domain/ProgramParticipants.java
  src/main/java/kusitms/jangkku/domain/program/domain/SelfUnderstanding.java
  src/main/java/kusitms/jangkku/domain/program/dto/ProgramDto.java
  src/main/java/kusitms/jangkku/domain/program/exception/ProgramErrorResult.java
  src/main/java/kusitms/jangkku/domain/user/domain/User.java
  src/main/java/kusitms/jangkku/global/exception/GlobalExceptionHandler.java
Labels: feat

#70 [feat, refactor] : 대화 완료 시 키워드 자동 생성 & 미완료 대화 삭제 기능 구현
  src/main/java/kusitms/jangkku/domain/clova/application/ClovaService.java
  src/main/java/kusitms/jangkku/domain/clova/application/ClovaServiceImpl.java
  src/main/java/kusitms/jangkku/domain/clova/dto/ClovaDto.java
  src/main/java/kusitms/jangkku/domain/clova/dto/Message.java
  src/main/java/kusitms/jangkku/domain/persona/application/DefinePersonaService.java
  src/main/java/kusitms/jangkku/domain/persona/application/DefinePersonaServiceImpl.java
  src/main/java/kusitms/jangkku/domain/persona/application/DesignPersonaService.java
  src/main/java/kusitms/jangkku/domain/persona/application/DesignPersonaServiceImpl.java
  src/main/java/kusitms/jangkku/domain/persona/application/DiscoverPersonaService.java
  src/main/java/kusitms/jangkku/domain/persona/application/DiscoverPersonaServiceImpl.java
  src/main/java/kusitms/jangkku/domain/persona/dao/DiscoverPersonaChattingRepository.java
  src/main/java/kusitms/jangkku/domain/persona/dao/DiscoverPersonaKeywordRepository.java
  src/main/java/kusitms/jangkku/domain/persona/domain/DiscoverPersona.java
  src/main/java/kusitms/jangkku/domain/persona/dto/DiscoverPersonaDto.java
  src/main/java/kusitms/jangkku/domain/token/application/TokenService.java
  src/main/java/kusitms/jangkku/domain/token/application/TokenServiceImpl.java
  src/main/java/kusitms/jangkku/domain/user/application/UserService.java
  src/main/java/kusitms/jangkku/domain/user/application/UserServiceImpl.java
  src/main/resources/application.yml
Labels: feat, refactor

#71 [refactor] : 프로그램 상세페이지 데이터 추가
  src/main/java/kusitms/jangkku/domain/program/application/ProgramServiceImpl.java
  src/main/java/kusitms/jangkku/domain/program/dto/ProgramDetailDto.java
  src/main/java/kusitms/jangkku/domain/program/exception/ProgramErrorResult.java
Labels: refactor

#72 [feat] : 카테고리별 페르소나 키워드 조회 API 구현 (GET)
  src/main/java/kusitms/jangkku/domain/persona/api/DiscoverPersonaController.java
  src/main/java/kusitms/jangkku/domain/persona/application/DiscoverPersonaService.java
  src/main/java/kusitms/jangkku/domain/persona/application/DiscoverPersonaServiceImpl.java
  src/main/java/kusitms/jangkku/domain/persona/constant/PersonaSuccessStatus.java
  src/main/java/kusitms/jangkku/domain/persona/exception/PersonaErrorResult.java
Labels: feat

#73 [fix] : DTO 값 중복 에러 해결
  src/main/java/kusitms/jangkku/domain/program/api/ProgramController.java
  src/main/java/kusitms/jangkku/domain/program/constant/FORM.java
  src/main/java/kusitms/jangkku/domain/program/constant/ProgramSuccessStatus.java
  src/main/java/kusitms/jangkku/domain/program/dao/SelfUnderstandingsRepository.java
  src/main/java/kusitms/jangkku/domain/program/domain/ProgramsInterest.java
  src/main/java/kusitms/jangkku/domain/program/domain/SelfUnderstanding.java
  src/main/java/kusitms/jangkku/domain/program/dto/ProgramDetailDto.java
Labels: bug, fix

#76 [Feat] : 마이페이지 신청한 경험 조회 api
  src/main/java/kusitms/jangkku/domain/program/dao/ProgramParticipantsRepository.java
  src/main/java/kusitms/jangkku/domain/program/exception/ProgramErrorResult.java
  src/main/java/kusitms/jangkku/domain/user/api/UserController.java
  src/main/java/kusitms/jangkku/domain/user/application/UserService.java
  src/main/java/kusitms/jangkku/domain/user/application/UserServiceImpl.java
  src/main/java/kusitms/jangkku/domain/user/constant/UserSuccessStatus.java
  src/main/java/kusitms/jangkku/domain/user/dto/UserDto.java
Labels: feat

#77 [refactor] : 자기이해 온오프라인 타입 수정
  src/main/java/kusitms/jangkku/domain/program/application/ProgramServiceImpl.java
  src/main/java/kusitms/jangkku/domain/program/constant/FORM.java
Labels: refactor

#79 [feat] : 키워드가 아예 존재하지 않는 경우 404 에러 처리 추가
  src/main/java/kusitms/jangkku/domain/persona/application/DiscoverPersonaServiceImpl.java
  src/main/java/kusitms/jangkku/domain/persona/exception/PersonaErrorResult.java
Labels: feat

#81 [Refactor] : 브랜딩 상세페이지 키워드 추출 로직 변경
  src/main/java/kusitms/jangkku/domain/program/api/ProgramController.java
  src/main/java/kusitms/jangkku/domain/program/application/ProgramService.java
  src/main/java/kusitms/jangkku/domain/program/application/ProgramServiceImpl.java
  src/main/java/kusitms/jangkku/domain/program/dto/ProgramDetailDto.java
  src/main/java/kusitms/jangkku/domain/program/dto/ProgramDto.java
Labels: refactor

#82 [refactor] : 카테고리별로 마무리 멘트 달라지도록 변경
  src/main/java/kusitms/jangkku/domain/persona/application/DiscoverPersonaServiceImpl.java
  src/main/java/kusitms/jangkku/domain/persona/constant/Question.java
  src/main/java/kusitms/jangkku/global/util/NumberUtil.java
Labels: feat, refactor, style

#83 [refactor] : @Transactional 어노테이션 클래스단으로 변경
  src/main/java/kusitms/jangkku/domain/clova/application/ClovaServiceImpl.java
  src/main/java/kusitms/jangkku/domain/persona/application/DefinePersonaServiceImpl.java
  src/main/java/kusitms/jangkku/domain/persona/application/DesignPersonaServiceImpl.java
  src/main/java/kusitms/jangkku/domain/persona/application/DiscoverPersonaServiceImpl.java
  src/main/java/kusitms/jangkku/domain/program/application/ProgramServiceImpl.java
  src/main/java/kusitms/jangkku/domain/token/application/TokenServiceImpl.java
  src/main/java/kusitms/jangkku/domain/user/application/UserServiceImpl.java
Labels: refactor

#85 [fix] : 미완료된 대화 삭제 로직 수정
  src/main/java/kusitms/jangkku/domain/persona/application/DiscoverPersonaServiceImpl.java
Labels: bug, fix

#86 [fix] : 이해하기 페르소나 질문 최종 픽스
  src/main/java/kusitms/jangkku/domain/persona/application/DiscoverPersonaServiceImpl.java
  src/main/java/kusitms/jangkku/domain/persona/constant/Question.java
Labels: bug, refactor, fix

#87 [refactor] : 정의하기 페르소나 키워드 최종 수정
  src/main/java/kusitms/jangkku/domain/persona/constant/Keyword.java
  src/main/java/kusitms/jangkku/domain/persona/constant/Question.java
Labels: refactor
